server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 300MB

  mail:
    username: 18398858464@163.com
    password: ZTUDFDOLCYGOFZJF
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.144.190:3307/picture?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  typeAliasesPackage: com.pst.picture.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
  type-enums-package: com.pst.picture.enums